from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    b=p.chromium.launch(); pg=b.new_page(viewport={'width':1400,'height':1000}); errs=[]; pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto('file://'+__import__('os').path.abspath('dist/hearth-sim.html')+''); pg.wait_for_timeout(1200)
    pg.evaluate("newWorld('q'); paused=true; for(let i=0;i<20500;i++){step(); for(const c of camps){ if(c.pit&&!c.everLit&&c.coals<=tick) lightTile(...c.pit);} } renderUI(true)")
    pg.wait_for_timeout(400)
    print('camps', pg.evaluate("camps.map(c=>c.name)"), pg.inner_text('#clock'))
    c=pg.evaluate("(()=>{const c=caves.find(c=>c.kind==='water'); const s=secOf(c.exit.x,c.exit.y); goto(s.sx,s.sy); return [c.exit.x,c.exit.y,c.mouth.x,c.mouth.y,s.sx,s.sy,c.story.join(' ')]})()")
    print('cave', c, pg.inner_text('#where'))
    box=pg.query_selector('#map').bounding_box()
    pg.mouse.move(box['x']+((c[0]-c[4]*28)+.5)*box['width']/28, box['y']+((c[1]-c[5]*20)+.5)*box['height']/20); pg.wait_for_timeout(300)
    print('mouth card:', pg.inner_text('#tip').replace('\n',' | ')[:220])
    pg.screenshot(path='cave-surface.png')
    pg.keyboard.press('['); pg.wait_for_timeout(300); print('level', pg.inner_text('#level'))
    pg.mouse.move(box['x']+((c[2]-c[4]*28)+.5)*box['width']/28, box['y']+((c[3]-c[5]*20)+.5)*box['height']/20); pg.wait_for_timeout(300)
    print('inside card:', pg.inner_text('#tip').replace('\n',' | ')[:220])
    pg.screenshot(path='cave-level-1.png')
    print('errors', errs); b.close()
