from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    b=p.chromium.launch(); pg=b.new_page(viewport={'width':1400,'height':1000}); errs=[]; pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto('file://'+__import__('os').path.abspath('dist/hearth-sim.html')+''); pg.wait_for_timeout(1200)
    pg.evaluate("newWorld('q'); paused=true; for(let i=0;i<20500;i++){step(); for(const c of camps){ if(c.pit&&!c.everLit&&c.coals<=tick) lightTile(...c.pit);} } renderUI(true)")
    pg.wait_for_timeout(400)
    print('camps', pg.evaluate("camps.map(c=>c.name)"), pg.inner_text('#clock'))
    h=pg.evaluate("(()=>{const h=hills[0]; const s=secOf(h.x,h.y); goto(s.sx,s.sy); return [h.x,h.y,h.storeys,s.sx,s.sy]})()")
    print('hill', h, pg.inner_text('#where'))
    pg.screenshot(path='hill-surface.png')
    pg.keyboard.press(']'); pg.wait_for_timeout(300); print('level', pg.inner_text('#level'))
    box=pg.query_selector('#map').bounding_box()
    pg.mouse.move(box['x']+((h[0]-h[3]*28)+.5)*box['width']/28, box['y']+((h[1]-h[4]*20)+.5)*box['height']/20); pg.wait_for_timeout(300)
    print('hill card:', pg.inner_text('#tip').replace('\n',' | ')[:220])
    pg.screenshot(path='hill-level1.png')
    print('errors', errs); b.close()
